quizBiblio/quizBiblio/urls.py
from django.contrib import admin

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', views.index, name='index'),
#     path('login/', LoginView.as_view(), name='login'),
#     path('register/', views.register, name='register'),
#     path("logout/", views.logout_view, name="logout"),
#     path('play-quiz/<int:quiz_id>', views.play_quiz, name='play-quiz'),
#     path('classement', views.rankings, name='classement'),
#     path('rankings-response', views.rankings_response, name='rankings-response'),
#     path('contact', views.contact_response, name="contact"),
# ]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from quizApps.views import QuizViewSet, ThemeViewSet, UserQuizViewSet, GroupViewSet
from quizApps.views import PropositionViewSet, QuestionViewSet

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'themes', ThemeViewSet)
router.register(r'quizzes', QuizViewSet)
router.register(r'userquizzes', UserQuizViewSet)
router.register(r'questions', QuestionViewSet)
router.register(r'propositions',PropositionViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(('auth_quizBiblio.routers', 'auth_quizBiblio'), namespace='auth-api')),
]

quizBiblio/quizApps/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from rest_framework import serializers

# Create your models here.
class Theme(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Quiz(models.Model):
    title = models.CharField(_('titre'), max_length=60, unique=True, error_messages={
                             'unique': 'Ce titre est déjà utilisé.'})
    description = models.TextField(_('description'), blank=True, null=True)
    first_theme = models.ForeignKey(Theme,verbose_name='1er thème', on_delete=models.CASCADE, related_name="first_theme")
    second_theme = models.ForeignKey(Theme,verbose_name='2nd thème (Facultatif)', on_delete=models.CASCADE, blank=True, null=True, related_name="second_theme")
    image = models.ImageField(_('image'), blank=True,
                              null=True, upload_to='uploads/')
    user = models.ManyToManyField(
        settings.AUTH_USER_MODEL , through='UserQuiz', related_name='quiz', blank=False)

    def __str__(self):
        return self.title


class UserQuiz(models.Model):
    score = models.IntegerField(_('score'), default=0)
    time = models.IntegerField(_('time'), default=0)
    is_creator = models.BooleanField(default=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    def __str__(self):
        return self.utilisateur.username


class Proposition(models.Model):
    propositionText = models.CharField(_('proposition'), max_length=255)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    question = models.ForeignKey(
        'Question', on_delete=models.CASCADE, related_name='+')
    is_correct = models.BooleanField(("Est correcte"), default=False)

    def __str__(self):
        return self.propositionText


class Question(models.Model):
    question = models.CharField(_('question'), max_length=255)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    explication = models.TextField(_('Explication'), blank=True, null=True)
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.question

quizBiblio/quizApps/views.py
from http import HTTPStatus
import imp
from re import I
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.forms import ValidationError
from django.http import HttpResponse, JsonResponse

from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.exceptions import APIException

from .models import Question, Quiz, Theme, UserQuiz, Proposition
from .serializers import PropositionSerializer, QuestionSerializer, QuizSerializer, ThemeSerializer, UserQuizSerializer, UserSerializer, GroupSerializer

User = get_user_model()

# class UserViewSet(viewsets.ModelViewSet):
#     """
#     API endpoint that allows users to be viewed or edited.
#     """
#     queryset = User.objects.all().order_by('-date_joined')
#     serializer_class = UserSerializer
#     permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all().order_by('name')
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]


class ThemeViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows themes to be viewed or edited.
    """
    queryset = Theme.objects.all()
    serializer_class = ThemeSerializer
    permission_classes = [permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        serializer = ThemeSerializer(data = request.data)
        serializer.is_valid(raise_exception=True)
        theme = serializer.validated_data['name']
        try:
            Theme.objects.get(name=theme)
            return JsonResponse({"error": "Ce thème existe déjà."})
        except Theme.DoesNotExist:
            Theme.objects.create(name=theme)
            return JsonResponse({"theme": theme})

class QuizViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows quizzes to be viewed or edited.
    """
    queryset = Quiz.objects.all().order_by('title')
    serializer_class = QuizSerializer
    permission_classes = [permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        serializer = QuizSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        if(request.data['first_theme'] == request.data['second_theme']):
            return JsonResponse({"error": "First and second themes can't be equals"}, status=HTTPStatus.BAD_REQUEST)
        return super().create(request, *args, **kwargs)

class UserQuizViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows user quizzes to be viewed or edited.
    """
    queryset = UserQuiz.objects.all().order_by('score')
    serializer_class = UserQuizSerializer
    permission_classes = [permissions.IsAuthenticated]

class QuestionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows questions to be viewed or edited.
    """
    queryset = Question.objects.all().order_by('question')
    serializer_class = QuestionSerializer
    permission_classes = [permissions.IsAuthenticated]

class PropositionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows propositions to be viewed or edited.
    """
    queryset = Proposition.objects.all().order_by('question')
    serializer_class = PropositionSerializer
    permission_classes = [permissions.IsAuthenticated]

quizBiblio/quizApps/templates/quizApps/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="QuizBiblio">
    <title>QuizBiblio</title>
    <link rel="stylesheet" href="{% static 'quizApps/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'quizApps/images/favicon.ico' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400;500;700&family=Karla:ital,wght@0,400;0,800;1,600&display=swap" rel="stylesheet">
    {% block styles %}{% endblock %}
</head>
<body class="bg-gray-800 font-medium">
    <header class="pt-5">
        <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-around md:flex-row md:px-6">
            <div class="flex flex-row items-center justify-between">
                <a href="{% url 'index' %}" class="text-white font-title font-bold text-3xl justify-end">Quiz<span class="text-teal-500">Biblio</span></a>
                <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline text-white" @click="open = !open" aria-label="menuToggle">
                    <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                      <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                      <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                </button>
            </div>
            <div :class="{'flex': open, 'hidden': !open}"  class=" flex-grow pb-4 md:pb-0 hidden md:flex justify-center md:justify-end md:flex-row items-center">
                <a href="{% url 'classement' %}" class="hover:text-teal-500 mx-5 text-white">Ranking</a>
                {% if not request.user.is_authenticated %}
                <a href="{% url 'login' %}" class="text-teal-500 mx-5 self-center text-center px-5 py-2 font-semibold rounded-lg hover:text-white">Log in</a>
                <a href="{% url 'register' %}" class="text-white mx-2 bg-teal-500 px-5 py-2 rounded-md hover:bg-white hover:text-teal-500">Register</a>
                {% else %}
                <div class="text-white px-5 border-r-2 border-white flex">
                    {% if 'quizApps.add_userquiz' in perms %}
                    <a href="{% url 'admin:index' %}" class="hover:text-teal-500">Admin panel</a>
                    {% endif %}
                    <p class="ml-8">{{request.user}}</p>
                </div>
                <a href="{% url 'logout' %}" class="text-teal-500 mx-5 self-center text-center px-5 py-2 font-semibold rounded-lg hover:text-white">Log out</a> 
                {% endif %}
            </div>
        </div>
    </header>

    {% block body %}
    {% endblock %}

    {% block footer %}
    <footer class="lg:flex justify-around mx-auto my-5">
        <div class="text-white font-title self-center text-center">
            <h1 class="font-semibold text-3xl ">QuizBiblio</h1>
            <p class="text-lg text-gray-400 max-w-lg mx-auto ">Test your literary, cinematographic and musical culture.</p>
            <p>© 2021 - Fabien Hannon </p>
        </div>
    </footer>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
    {% block scripts %}
    {% endblock %}
</body>

quizBiblio/quizApps/templates/quizApps/classement.html
{% extends 'quizApps/base.html' %} {% block body %}
<div class="overflow-x-auto">
    <div class="min-w-screen flex justify-center bg-gray-800 font-sans overflow-hidden">
        <div class="max-w-screen-md lg:w-5/6">
            <h1 class="text-center text-4xl text-white my-10">Ranking per theme</h1>
            <div class="flex justify-evenly flex-wrap">
                {% for theme in themes %}
                <button type="button" id="{{theme.id}}" onclick="callAjax($(this));return false;" class="text-gray-300 focus:bg-teal-500 focus:text-gray-900 shadow-lg bg-gray-900 px-10 font-semibold py-2 m-2 rounded-full">{{theme}}</button> 
                {% endfor %}
            </div>
            <div class="bg-gray-900 shadow-md rounded my-6" id="table">
            </div>
            {% if themes %}
            <p class="text-gray-400 text-center" id="message">Select a theme</p>
            {% else %}
            <p class="text-gray-400 text-center">No theme available.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %} {% block footer %} {% endblock %} {% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
    function callAjax($this) {
        let id = $this.attr("id");
        $.ajax({
            method: "GET",
            url: "rankings-response",
            "dataType": "html",
            "data": {
                id: id
            },
            success: function(data) {
                $("#table").html(data);
                $("#message").hide();
            }
        });
    }
</script>
{% endblock %}

quizBiblio/quizApps/templates/quizApps/classement_table.html
<table class="min-w-max w-full table-auto">
    <thead>
        <tr class="bg-teal-500 text-gray-100 uppercase text-sm leading-normal">
            <th class="py-3 px-6 text-center">Position</th>
            <th class="py-3 px-6 text-center">User</th>
            <th class="py-3 px-6 text-center">Points</th>
        </tr>
    </thead>
    <tbody class="text-gray-100 text-lg font-light">
        {% for user in users %}
        <tr>
            <td class="py-3 px-6 text-center">
                <span class="py-1 px-3 rounded-full">{{forloop.counter}}</span>
            </td>
            <td class="py-3 px-6 text-center">
                <span class="py-1 px-3 rounded-full">{{user.username}}</span>
            </td>
            <td class="py-3 px-6 text-center">
                <span class=" text-white py-1 px-3 rounded-full">{{user.score}}</span>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="py-3 px-6 text-center" colspan="3">
                <span class="py-1 px-3 rounded-full">No user has a score on quizzes related to this topic.</span>
            </td>
        </tr>
        {% endfor %}
</table>

quizBiblio/quizApps/templates/quizApps/index.html
{% extends 'quizApps/base.html' %} {% load static %} {% block body %}
<section class="flex lg:h-screen lg:max-w-6xl items-center mx-auto">
    <section class="lg:flex mx-auto">
        <article class="max-w-lg  mx-auto mt-8 text-center lg:text-left">
            <h1 class="text-white text-4xl lg:text-5xl font-bold text-center lg:text-left"> Test your <span class="text-teal-500">literary, cinematographic </span> and <span class="text-teal-500">musical </span> culture !</h1>
            <p class="font-display text-white font-normal text-sm text-center lg:text-left max-w-md my-8">
            Develop your knowledge on different topics and test your general knowledge</p>
            <a href="#button-all-quiz" class="text-gray-800 bg-teal-500 px-8 py-3
                    rounded-md hover:bg-white hover:text-teal-500 ">Start a quiz</a>
        </article>
        <aside class="mt-20 lg:mt-0 mx-auto lg:ml-40">
            <img src="{% static 'quizApps/images/demo2.png' %}" alt="app demo" width="450px">
        </aside>
    </section>
</section>

<section class="bg-gray-700 pt-8 pb-52">
    <div class="container mx-auto">
        <h1 class="text-white text-4xl text-center">Play many quizzes !</h1>
        <article class="font-display p-2 mt-8 mx-auto flex justify-center flex-wrap" id="button-all-quiz">
            {% for quiz in quizzes %}
            <a href="{% url 'play-quiz' quiz.id %}" class="bg-gray-800 text-center w-3/12 p-5 mx-auto my-5 rounded-3xl card">
                {% if quiz.image %}
                <img src="{{MEDIA_URL}}{{quiz.image.url}}" alt="image {{quiz.id}}" class="mx-auto w-48 object-scale-down">
                {% endif %}
                <h1 class="text-4xl font-extrabold text-white">{{quiz}}</h1>
                <h2 id="themes" class="text-gray-300 text-lg">{{quiz.theme1}}
                    <span class="ml-8">{% if quiz.theme2 %}{{quiz.theme2}}{% endif %}</span>
                </h2>
                <div class="flex  text-lg font-semibold font-title justify-center text-white">
                    <p class="text-teal-500 w-32">{{quiz.question_set.count}} Question{% if quiz.question_set.count > 1 %}s{% endif %}</p>
                    <p class="w-32">By {{quiz.userquiz_set.first}}</p>
                </div>
            </a> {% empty %}
            <p class="text-white">No quiz available.</p>
            {% endfor %}
        </article>
    </div>
</section>
{% endblock %} {% block scripts %}
<script>
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();

            document.querySelector(this.getAttribute('href')).scrollIntoView({
                behavior: 'smooth'
            });
        });
    });
</script>
{% endblock %}

quizBiblio/quizApps/templates/quizApps/play-quiz.html
{% extends 'quizApps/base.html' %}
{% load static %}

{% block body %}
<section class="mx-auto mt-10 max-w-3xl justify-center items-center">
    {% if quiz.image %}
    <img src="{{MEDIA_URL}}{{quiz.image.url}}" alt="{{quiz.title}} image" class="mx-auto w-56" />
    {% endif %}
    <div class="ml-8 text-center max-w-2xl">
        <h1 class="text-white text-5xl mt-5 font-bold">{{ quiz.title }}</h1>
        <div class="flex mt-2 justify-center">
            <h2 class="text-gray-400 mt-2">By {{quiz.userquiz_set.first}}</h2>
            <h3 class="text-gray-400 mt-2">&#x1F516; {{quiz.theme1}} {% if quiz.theme2 %} -
                {{quiz.theme2}}{% endif %} </h3>
        </div>
        <p class="text-white mt-2">{{quiz.description}}</p>
        {% if validList %}
        <p class="text-white mt-2 text-2xl">&#x1F3C6; <span id="score">{{score}}</span> points</p>
        <p class="text-white mt-2 text-md">You correctly answered {{rightAnswers}} out of {{questions.items|length}} questions</p>
        {% endif %}
    </div>
</section>

{% if not validList %}
<button id="start"
    class="flex items-center text-teal-500 mx-auto text-3xl  mt-10 focus:outline-none hover:text-white">Start now
    <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 ml-2 mt-1" viewBox="0 0 20 20"
        fill="currentColor">
        <path fill-rule="evenodd"
            d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 1.414L10.586 9H7a1 1 0 100 2h3.586l-1.293 1.293a1 1 0 101.414 1.414l3-3a1 1 0 000-1.414z"
            clip-rule="evenodd" />
    </svg>
</button>
<div class="hidden">
    <p id="timer" class="text-center text-white text-4xl font-title">0</p>
</div>
{% endif %}


<form class="opacity-0 hidden my-14" action="{% url 'play-quiz' quiz.id %}" method="post" id="quiz">
    {% csrf_token %}
    {% for question, props in questions.items %}
    <section
        class="max-w-2xl mx-auto mt-5 bg-gray-700 text-white px-8 py-5 rounded-lg font-title shadow-lg">
        <h2 class="font-semibold ">Question {{forloop.counter}}</h2>
        {% if question.image %}
        <img src="{{MEDIA_URL}}{{question.image.url}}" alt="{{question.title}} image" class="mx-auto w-48"/>
        {% endif %}
        <h1 class="text-teal-500 text-4xl mt-2 font-bold ">{{question}}</h1>
        {% if validList %}
        <div class="hidden" id="infos-{{question.id}}">
            <p id="message-{{question.id}}" class="text-teal-500 mt-2 font-bold ">Correct !</p>
            <p id="desc" class="font-display">{{question.explication}}</p>
        </div>
        {% endif %}
    </section>
    <section
        class="max-w-2xl mx-auto my-5 text-white font-display flex-wrap flex justify-evenly items-center">
        {% for prop in props %}
        {% if validList %}
        <p class="bg-gray-700 rounded-lg px-8 py-4 my-5 flex justify-center shadow-lg"
            id="{{prop.id}}">
            {% if prop.image %}
            <img src="{{MEDIA_URL}}{{prop.image.url}}" alt="image-prop-{{prop.id}}" width="200px" />
            {% else %}
            {{prop}}
            {% endif %}
        </p>
        {% else %}
        <div>
            <input class="proposition" type="checkbox" name="question-{{question.id}}" value="{{prop.id}}"
                id="{{prop.id}}">
            <label
                class="bg-gray-700 rounded-lg px-8 py-4 my-5 flex justify-center shadow-lg cursor-pointer"
                for="{{prop.id}}">
                {% if prop.image %}
                <img src="{{MEDIA_URL}}{{prop.image.url}}" alt="image-prop-{{prop.id}}" width="200px" />
                {% else %}
                {{prop}}
                {% endif %}
            </label>
        </div>
        {% endif %}
        {% endfor %}
    </section>
    {% endfor %}
    {% if not validList %}
    <input type="submit" id="submitBtn"
        class="mx-auto block bg-teal-500 px-8 py-4 text-white font-display font-bold rounded text-xl cursor-pointer hover:bg-white hover:text-teal-500">
    {% else %}
    <a href="{% url 'index' %}" class="mx-auto w-max block text-center bg-teal-500 px-8 py-4 text-white font-display font-bold rounded text-xl 
        cursor-pointer hover:bg-white hover:text-teal-500">Main menu</a>
    {% endif %}

    <input type="hidden" name="time" id="time" value="" />

</form>
{% endblock %}

{% block footer %}
{% endblock %}

{% block scripts %}
{{validList|json_script:'valid'}}
{{choices|json_script:'choices'}}
{{choicesDict|json_script:'choicesDict'}}
{{validDict|json_script:'validDict'}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
    let nbQuestions = "{{nbQuestion}}";
    for (let i = 1; i <= nbQuestions; i++) {
        let prop = $("input[name=question-" + i + "]:checked");
        prop.attr("selected", false);
    }

    $(document).ready(() => {
        let valids = JSON.parse(document.getElementById("valid").textContent);
        let choices = JSON.parse(document.getElementById("choices").textContent);
        let choicesDict = JSON.parse(document.getElementById("choicesDict").textContent);
        let validDict = JSON.parse(document.getElementById("validDict").textContent);


        for (let i = 0; i < valids.length; i++) {
            let valid = $("#" + valids[i]).addClass("bg-teal-600").removeClass("bg-gray-700");
        }

        for (let i = 0; i < choices.length; i++) {
            let choice = $("#" + choices[i]).addClass("border-4");
            if (valids.includes(parseInt(choice.attr("id")))) {
                choice.addClass("border-teal-400").removeClass("border-red-500");
            } else {
                choice.addClass("border-red-500");
            }
        }
        for (key in choicesDict) {
            $("#infos-" + key.replace('question', '')).removeClass("hidden");
            const array2Sorted = validDict[key].slice().sort();
            var test = choicesDict[key].length === validDict[key].length && choicesDict[key].slice().sort().every(function (value, index) {
                return value === array2Sorted[index];
            });
            message = $("#message-" + key.replace('question', ''));
            if (test == true) {
                message.text("Correct \u{1F60E}").removeClass("text-red-500").addClass("text-teal-500");

            } else {
                message.text("Wrong \u{1F625}").removeClass("text-teal-500").addClass("text-red-500");
            }
        }

        window.addEventListener("pageshow", () => {
            $('#quiz')[0].reset();
        });

        function hello() {
            $("#quiz").removeClass("hidden");
            if ($('form').css('opacity') == 0) {
                $('form').css('opacity', 1);
            }
            else {
                $('form').css('opacity', 0);
            }
            $("#start+div").removeClass("hidden");
            var initialTime = Date.now();

            setInterval(() => {
                var timeDifference = Date.now() - initialTime;
                var formatted = convertTime(timeDifference);
                $("#timer").text('' + formatted);
                document.getElementById("time").value = Math.floor(timeDifference / 1000);
            })

            function convertTime(miliseconds) {
                var totalSeconds = Math.floor(miliseconds / 1000);
                var minutes = Math.floor(totalSeconds / 60);
                var seconds = totalSeconds - minutes * 60;
                return minutes + ':' + seconds + "s";
            }
            $("#start").addClass("hidden");
        }

        if (!valids) {
            document.getElementById("start").addEventListener("click", hello);
        } else {
            $('form').css('opacity', 1).removeClass("hidden");
        }
    });
</script>
{% endblock %}